name: Checking formatting
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.0
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install gdtoolkit
        run: |
          python -m pip install --upgrade pip
          pip install gdtoolkit
      - name: Check formatting with gdformat
        run: |
          gdformat $(find . -name '*.gd')
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Sh1co'
          git config --global user.email 'shico.m.nafee@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated code formatting"
          git push