name: Checking formatting
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10.0
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.0"
      - name: Install gdtoolkit
        run: |
          python -m pip install --upgrade pip
          pip install gdtoolkit
      - name: Check formatting with gdformat
        run: |
          gdformat $(find . -name '*.gd')